name: "Setup node dependencies"
description: "Checks out the repository, sets up Node.js, installs dependencies via npm ci and generates the Prisma client"

runs:
  using: "composite"
  steps:
    - name: "Checkout repository"
      uses: actions/checkout@v7

    - name: "Set up Node.js"
      uses: actions/setup-node@v7
      with:
        node-version: "24.21"
        cache: "npm"

    - name: "Install dependencies"
      run: npm ci
      shell: bash

    - name: "Generate prisma files"
      run: "npx prisma generate"
      shell: bash

