name: Node.js CI
run-name: "Node.js CI run by @${{ github.actor }} on ${{ github.ref_name }}"

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev

  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ "22.x", "24.x" ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{
            hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Clean install dependencies
        run: npm ci

      - name: Checking code linting
        run: npm run lint

      - name: Run tests
        run: npm test
