name: "CI"

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v7

      - name: "Setup node dependencies"
        uses: ./.github/actions/setup-node-deps

      - name: "Build project"
        run: npm run build

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v7

      - name: "Setup node dependencies"
        uses: ./.github/actions/setup-node-deps

      - name: "Check types"
        run: npm run typecheck

      - name: "Checkout code linting"
        run: npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v7

      - name: "Setup node dependencies"
        uses: ./.github/actions/setup-node-deps

      - name: "Run api tests"
        run: npm run test

      - name: "Run endo-to-end api tests"
        run: npm run test:e2e



